#
# Default subroutes configuration for the Feeder package
# Copy this before the TYPO3.Neos subroutes in your project's Routes.yaml
#

-
  name: 'RSS 2.0 Syndication'
  uriPattern: '{node}.rss2'
  defaults:
    '@package': 'Nezaniel.Syndicator'
    '@controller': 'Node'
    '@action': 'syndicate'
    '@format': 'rss2'
  routeParts:
    node:
      handler: TYPO3\Neos\Routing\FrontendNodeRoutePartHandlerInterface

-
  name: 'Atom Syndication'
  uriPattern: '{node}.atom'
  defaults:
    '@package': 'Nezaniel.Syndicator'
    '@controller': 'Node'
    '@action': 'syndicate'
    '@format': 'atom'
  routeParts:
    node:
      handler: TYPO3\Neos\Routing\FrontendNodeRoutePartHandlerInterface